from dotenv import load_dotenv
load_dotenv()

from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI


def generate_joke(topic: str) -> str:
    """
    Generate a joke about a given topic using an LLM.

    Parameters
    ----------
    topic : str
        The topic of the joke (e.g., "cats", "dogs", "programmers").

    Returns
    -------
    str
        The joke generated by the language model.

    Steps
    -----
    1. Create a reusable prompt template.
    2. Initialize the LLM model.
    3. Fill the prompt template with the provided topic.
    4. Send the prompt to the LLM.
    5. Return the generated response.
    """

    # 1️⃣ Create a reusable prompt template
    prompt_template = PromptTemplate.from_template(
        "Tell me a joke about {topic}"
    )

    # 2️⃣ Initialize the LLM
    llm = ChatOpenAI(
        model="gpt-4o-mini",
        temperature=0.8,  # higher temperature = more creative responses
    )

    # 3️⃣ Fill the template with the topic
    prompt = prompt_template.invoke({"topic": topic})

    # 4️⃣ Send the prompt to the LLM
    response = llm.invoke(prompt)

    # 5️⃣ Return the generated joke
    return response.content


if __name__ == "__main__":
    """
    Entry point of the script.

    Calls the generate_joke function and prints the result.
    """

    topic = "dogs"
    joke = generate_joke(topic)

    print("\nGenerated Joke:\n")
    print(joke)