from dotenv import load_dotenv
load_dotenv()

from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI


def generate_joke(topic: str, style: str) -> str:
    """
    Generate a joke using multiple prompt variables.

    Parameters
    ----------
    topic : str
        The topic of the joke (e.g., "cats", "AI", "programmers").

    style : str
        The style of the joke (e.g., "dad joke", "sarcastic", "dark humor").

    Returns
    -------
    str
        The joke generated by the language model.

    Steps
    -----
    1. Create a reusable prompt template with multiple variables.
    2. Initialize the LLM model.
    3. Fill the template with real values.
    4. Send the prompt to the LLM.
    5. Return the generated response.
    """

    # 1. Create a prompt template with multiple variables
    prompt_template = PromptTemplate.from_template(
        """
        Create a {style} joke about {topic}.
        Make it short and funny.
        """
    )

    # 2. Initialize the LLM
    llm = ChatOpenAI(
        model="gpt-4o-mini",
        temperature=0.8
    )

    # 3. Fill the template with actual values
    prompt = prompt_template.invoke({
        "topic": topic,
        "style": style,
    })

    # 4. Send prompt to the LLM
    response = llm.invoke(prompt)

    # 5. Return the generated joke
    return response.content


if __name__ == "__main__":
    """
    Entry point of the script.

    Calls the generate_joke function and prints the result.
    """

    topic = "dog"
    style = "dad joke"

    joke = generate_joke(topic, style)

    print("\nGenerated Joke:\n")
    print(joke)